### variabili di configurazione per la compilazione ###
USE_DEBUG = yes
USE_CLANG = no
CFLAGS = -DPBC_SUPPORT
CFLAGS += -Iinclude
LDFLAGS =
LIBS = m gmp nettle hogweed pbc 
PROGS = $(basename $(wildcard test-*.c) $(wildcard attack-*.c) $(wildcard example-*.c))
