### Variabili di configurazione per la compilazione ###
USE_DEBUG = yes
USE_CLANG = no
CFLAGS = -DPBC_SUPPORT -Iinclude -Ilib
LDFLAGS =
LIBS = m gmp nettle hogweed pbc
SRC_DIRS = src lib
SRCS = $(wildcard $(addsuffix /*.c,$(SRC_DIRS)))
OBJS = $(patsubst %.c,%.o,$(SRCS))
TEST = test-OwnerSigner
OBJR = $(wildcard lib/lib-*.o) $(wildcard src/lib-*.o) $(wildcard test/test-*.o)

$(TEST): $(OBJS) test/test-OwnerSigner.o
	$(CC) $(LDFLAGS) -o $@ $^ $(foreach lib,$(LIBS),-l$(lib))
    
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	@echo "Rimuovendo i seguenti file oggetto e l'eseguibile:"
	@echo $(OBJR) $(TEST)
	rm -f $(OBJR) $(TEST)
	@echo "Pulizia completata."

